ALTER TABLE epatraktor.utskick_bilaga DROP CONSTRAINT IF EXISTS FK_utskick_bilaga_utskick_id;
ALTER TABLE epatraktor.bilagekoppling DROP CONSTRAINT IF EXISTS FK_bilagekoppling_persmeddid;
ALTER TABLE epatraktor.meddelandetext DROP CONSTRAINT IF EXISTS FK_meddelandetext_persmeddid;
ALTER TABLE epatraktor.meddelande_header DROP CONSTRAINT IF EXISTS FK_meddelande_header_persmeddtyp;
ALTER TABLE epatraktor.meddelande_header DROP CONSTRAINT IF EXISTS FK_meddelande_header_meddfrågekategori;
ALTER TABLE epatraktor.meddelande_header DROP CONSTRAINT IF EXISTS FK_meddelande_header_persmeddstatus;
DROP TABLE IF EXISTS epatraktor.massutskick;
DROP TABLE IF EXISTS epatraktor.debiteringsuppgift;
DROP TABLE IF EXISTS epatraktor.informationsprodukt;
DROP TABLE IF EXISTS epatraktor.publicering_jobb;
DROP TABLE IF EXISTS epatraktor.informationssamband;
DROP TABLE IF EXISTS epatraktor.utskick_installning;
DROP TABLE IF EXISTS epatraktor.kuvert;
DROP TABLE IF EXISTS epatraktor.dokument;
DROP TABLE IF EXISTS epatraktor.utskick_bilaga;
DROP TABLE IF EXISTS epatraktor.utskick;
DROP TABLE IF EXISTS epatraktor.kund;
DROP TABLE IF EXISTS epatraktor.bilagekoppling;
DROP TABLE IF EXISTS epatraktor.bilaga;
DROP TABLE IF EXISTS epatraktor.meddelandetext;
DROP TABLE IF EXISTS epatraktor.meddelande_header;
DROP TABLE IF EXISTS epatraktor.fragekategori;
DROP TABLE IF EXISTS epatraktor.meddelandestatus;
DROP TABLE IF EXISTS epatraktor.meddelandetyp;
